type Query {
    locus(chromosome: String, start: Int, end: Int): DrawableLocus
    diseaseTable(efoId: String, offset: Int, limit: Int): DiseaseTable
}
type Gene {
    # The Ensembl gene identifier.
    id: String
    symbol: String
    chromosome: String
    tss: Int
    start: Int
    end: Int
    forwardStrand: Boolean
    canonicalTranscript: CanonicalTranscript
}
type Variant {
    id: String
    chromosome: String
    position: Int
}
type LeadVariant {
    id: String
    chromosome: String
    position: Int
}
type Disease {
    id: String
    name: String
}
type GeneVariant {
    id: String
    geneId: String
    geneSymbol: String
    geneChromosome: String
    geneTss: Int
    variantId: String
    variantChromosome: String
    variantPosition: Int
    # TODO: otG2VScore: Float
    vep: Float
    gtex: Float
    pchic: Float
    fantom5: Float
    dhs: Float
    nearest: Boolean
}
type VariantLeadVariant {
    id: String
    variantId: String
    variantChromosome: String
    variantPosition: Int
    leadVariantId: String
    leadVariantChromosome: String
    leadVariantPosition: Int
    r2: Float
}
type LeadVariantDisease {
    id: String
    leadVariant: LeadVariant
    disease: Disease
    gwasPValue: Float
}
type CanonicalTranscript {
    id: String
    start: Int
    end: Int
    forwardStrand: Boolean
    exons: [Exon]
    tss: Int
    translationStart: Int
    translationEnd: Int
}
type Exon {
    id: String
    start: Int
    end: Int
}
type DrawableLocus {
    genes: [Gene]
    variants: [Variant]
    leadVariants: [LeadVariant]
    diseases: [Disease]
    geneVariants: [GeneVariant]
    variantLeadVariants: [VariantLeadVariant]
}
type DiseaseTable {
    rows: [FullTableRow]
    total: Int
    offset: Int
    limit: Int
}
type FullTableRow {
    index: Int
    geneId: String
    geneSymbol: String
    geneChromosome: String
    geneTss: Int
    variantId: String
    variantChromosome: String
    variantPosition: Int
    leadVariantId: String
    efoId: String,
    efoName: String,
    vep: Float
    gtex: Float
    pchic: Float
    fantom5: Float
    dhs: Float
    nearest: Boolean
    r2: Float
    gwasPValue: Float
    gwasOddsRatio: Float
    gwasBeta: Float
    gwasSize: Int
    gwasPMId: String
    gwasStudy: String
}
