type Query {
    locus(chromosome: String, start: Int, end: Int, g2VMustHaves: [String], g2VScore: [Float] r2: [Float], gwasPValue: [Float], selectedId: String, selectedType: String): DrawableLocus
    locusTable(chromosome: String, start: Int, end: Int, g2VMustHaves: [String], g2VScore: [Float] r2: [Float], gwasPValue: [Float], selectedId: String, selectedType: String, offset: Int, limit: Int): LocusTable
    diseaseTable(efoId: String, offset: Int, limit: Int): DiseaseTable
}
type Gene {
    # The Ensembl gene identifier.
    id: String
    symbol: String
    chromosome: String
    tss: Int
    start: Int
    end: Int
    forwardStrand: Boolean
    # canonicalTranscript: CanonicalTranscript
    exons: [[Int]]
    selected: Boolean
}
type Variant {
    id: String
    # chromosome: String
    position: Int
    selected: Boolean
}
type LeadVariant {
    id: String
    # chromosome: String
    position: Int
    selected: Boolean
}
type Disease {
    id: String
    name: String
    selected: Boolean
}
type GeneVariant {
    id: String
    geneId: String
    geneSymbol: String
    # geneChromosome: String
    geneTss: Int
    # canonicalTranscript: CanonicalTranscript
    variantId: String
    # variantChromosome: String
    variantPosition: Int
    otG2VScore: Float
    vep: Float
    gtex: Float
    pchic: Float
    fantom5: Float
    dhs: Float
    nearest: Boolean
    selected: Boolean
}
type VariantLeadVariant {
    id: String
    variantId: String
    # variantChromosome: String
    variantPosition: Int
    leadVariantId: String
    # leadVariantChromosome: String
    leadVariantPosition: Int
    r2: Float
    selected: Boolean
}
type LeadVariantDisease {
    id: String
    leadVariantId: String
    # leadVariantChromosome: String
    leadVariantPosition: Int
    efoId: String
    efoName: String
    gwasPValue: Float
    gwasOddsRatio: Float
    gwasBeta: Float
    gwasStudy: String
    gwasPMId: String
    gwasSize: Int
    selected: Boolean
}
type CanonicalTranscript {
    id: String
    start: Int
    end: Int
    forwardStrand: Boolean
    exons: [[Int]]
    tss: Int
    translationStart: Int
    translationEnd: Int
}
type DrawableLocus {
    genes: [Gene]
    variants: [Variant]
    leadVariants: [LeadVariant]
    diseases: [Disease]
    geneVariants: [GeneVariant]
    variantLeadVariants: [VariantLeadVariant]
    leadVariantDiseases: [LeadVariantDisease]
    maxGwasPValue: Float
}
type LocusTable {
    rows: [FullTableRow]
    total: Int
    offset: Int
    limit: Int
}
type DiseaseTable {
    rows: [FullTableRow]
    total: Int
    offset: Int
    limit: Int
}
type FullTableRow {
    index: Int
    geneId: String
    geneSymbol: String
    geneChromosome: String
    geneTss: Int
    variantId: String
    variantChromosome: String
    variantPosition: Int
    leadVariantId: String
    efoId: String
    efoName: String
    otG2VScore: Float
    vep: Float
    gtex: Float
    pchic: Float
    fantom5: Float
    dhs: Float
    nearest: Boolean
    r2: Float
    gwasPValue: Float
    gwasOddsRatio: Float
    gwasBeta: Float
    gwasSize: Int
    gwasPMId: String
    gwasStudy: String
}
